apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-demo-staging
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: releases
    notifications.argoproj.io/subscribe.on-health-degraded.slack: releases
spec:
  project: default

  source:
    repoURL: https://github.com/bernadin/cicd-demo
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-demo-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
