# Staging environment overrides
image:
  tag: "a4ceaf660bcce4b30995825d931037d7cd8fd57f"

replicaCount: 1

autoscaling:
  enabled: false

rollout:
  strategy: canary
  steps:
    - setWeight: 50
    - pause: { duration: 10s }
    - setWeight: 100
  analysis:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
