# Staging environment overrides
image:
  tag: "c0266b6eb1090185b9c6d2e3a727fa0201c2f03f"

replicaCount: 1

autoscaling:
  enabled: false

rollout:
  strategy: canary
  steps:
    - setWeight: 50
    - pause: { duration: 10s }
    - setWeight: 100
  analysis:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
