# Staging environment overrides
image:
  tag: "4432fede6d63e9847943d34ffeee809d2602c53f"

replicaCount: 1

autoscaling:
  enabled: false

rollout:
  strategy: canary
  steps:
    - setWeight: 50
    - pause: { duration: 10s }
    - setWeight: 100
  analysis:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
